In [ ]:
import torch
import torch.nn as nn

reviews = [
    "the movie was great",
    "i hated this movie",
    "the story was amazing",
    "the acting was excellent",
    "this movie was fantastic",
    "i really enjoyed this",
    "the movie felt boring",
    "the story was interesting",
    "i hated this movie",
    "characters were very good"
]

# Get every unique word
words = sorted({w for r in reviews for w in r.split()})

# word -> integer ID
stoi = {w: i for i, w in enumerate(words)}

# Convert words to integer IDs
def encode(text):
    return torch.tensor([stoi[w] for w in text.split()])

print("Vocabulary:", words)
print("Vocabulary size:", len(stoi))

# Create embedding layer
embedding = nn.Embedding(
    num_embeddings=len(stoi),
    embedding_dim=4
)

# Encode a bigger review
review = "the movie was great"

ids = encode(review)

print("\nWord IDs:")
print(ids)

# Convert IDs into embeddings
vectors = embedding(ids)

print("\nEmbedding vectors:")
print(vectors)

# Average all word vectors
sentence_vector = vectors.mean(dim=0)

print("\nSentence vector:")
print(sentence_vector)

print("\nSentence vector shape:")
print(sentence_vector.shape)
class SentimentNet(nn.Module):
    def __init__(self, vocab_size  , dim = 0):
        super().__init__()
        self.emb = nn.Embedding(vocab_size , dim)
        self.fc = nn.Linear(dim , 2)

    def forward(self , ids):
        pooled = self.emb(ids).mean(dim = 0 , keepdim = True)
        return self.fc(pooled)
    
        
        
train = [
    ("the movie was great", 1),
    ("i hated this movie", 0),
    ("the story was amazing", 1),
    ("the acting was excellent", 1),
    ("this movie was fantastic", 1),
    ("i really hated this", 0),
]
model = SentimentNet(len(stoi) , dim = 0)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters() , lr = 0.05)

for epoch in range(200):
    losses = [loss_fn(model(encode(t)) , torch.tensor([y])) for t , y in train]
    loss = torch.stack(losses).mean()
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"epoch : {epoch} , loss : {loss}")

prediction = model(encode("i really hated this"))
prediction
prediction = prediction.argmax().item()
prediction



Vocabulary: ['acting', 'amazing', 'boring', 'characters', 'enjoyed', 'excellent', 'fantastic', 'felt', 'good', 'great', 'hated', 'i', 'interesting', 'movie', 'really', 'story', 'the', 'this', 'very', 'was', 'were']
Vocabulary size: 21

Word IDs:
tensor([16, 13, 19,  9])

Embedding vectors:
tensor([[-1.3066,  0.3738, -0.5702, -0.3264],
        [-1.7414,  0.0635,  0.3201, -1.7375],
        [-0.7630, -0.8355,  1.1917,  0.4767],
        [ 0.5524, -0.1206, -0.4414,  0.3090]], grad_fn=<EmbeddingBackward0>)

Sentence vector:
tensor([-0.8146, -0.1297,  0.1251, -0.3196], grad_fn=<MeanBackward1>)

Sentence vector shape:
torch.Size([4])
