# Fit y = 2x + 1

In [1]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Using: cuda
GPU: NVIDIA GeForce RTX 4060 Laptop GPU


In [3]:
import torch
import torch.nn as nn
X = torch.linspace(-1, 1, 50).reshape(-1, 1).to(device)
Y = (2 * X + 1).to(device)

model = nn.Linear(1, 1).to(device)



loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.1
)


for step in range(200):
    print(list(model.parameters())) 
    pred = model(X) #Forward
    loss = loss_fn(pred , Y) #how wrong
    optimizer.zero_grad() #resets grads
    loss.backward() #autograd
    optimizer.step() #update w and b

print(model.weight.item(), model.bias.item())


[Parameter containing:
tensor([[-0.8660]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.3670], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[-0.6671]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.4936], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[-0.4821]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5949], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[-0.3099]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6759], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[-0.1496]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7407], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[-0.0004]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7926], device='cuda:0', requires_grad=True)]
[Parameter containing:
tensor([[0.1384]], device='cu

# Digits : SGD VS ADAM


In [12]:
import torch
import torch.nn as nn
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load data
X, y = load_digits(return_X_y=True)

# Train/test split
X_tre, X_tes, y_tre, y_tes = train_test_split(
    X, y,
    train_size=0.8,
    random_state=42,
    stratify=y
)

# Standardization
sc = StandardScaler()
Xtr = torch.tensor(sc.fit_transform(X_tre), dtype=torch.float32)
Xtes = torch.tensor(sc.transform(X_tes), dtype=torch.float32)

# Labels
ytr = torch.tensor(y_tre, dtype=torch.long)
ytes = torch.tensor(y_tes, dtype=torch.long)

# Model
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 10)
)

# Loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

# Training
for epoch in range(60):
    pred = model(Xtr)
    loss = loss_fn(pred, ytr)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 5 == 0:
        lr = optimizer.param_groups[0]['lr']
        print(f"Epoch {epoch+1:3d} | lr: {lr:.4f} | loss: {loss.item():.4f}")

    

# Evaluation
with torch.no_grad():
    pred = model(Xtes)
    acc = (pred.argmax(1) == ytes).float().mean()
    
    print("Accuracy:", acc.item())
    

Epoch   5 | lr: 0.1000 | loss: 0.2591
Epoch  10 | lr: 0.1000 | loss: 0.0898
Epoch  15 | lr: 0.1000 | loss: 0.0212
Epoch  20 | lr: 0.1000 | loss: 0.0043
Epoch  25 | lr: 0.1000 | loss: 0.0014
Epoch  30 | lr: 0.1000 | loss: 0.0007
Epoch  35 | lr: 0.1000 | loss: 0.0003
Epoch  40 | lr: 0.1000 | loss: 0.0002
Epoch  45 | lr: 0.1000 | loss: 0.0001
Epoch  50 | lr: 0.1000 | loss: 0.0001
Epoch  55 | lr: 0.1000 | loss: 0.0001
Epoch  60 | lr: 0.1000 | loss: 0.0000
Accuracy: 0.9666666388511658


In [2]:
import numpy as np
